CREATE TABLE IF NOT EXISTS producao.tbl_status_producao
(
    id_status_producao integer GENERATED BY DEFAULT AS IDENTITY,
    status_producao character varying(100) NOT NULL,
    ordem integer NOT NULL DEFAULT 0,
    ativo boolean NOT NULL DEFAULT true,
    cadastrado_em timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT tbl_status_producao_pkey PRIMARY KEY (id_status_producao),
    CONSTRAINT tbl_status_producao_status_key UNIQUE (status_producao)
);

INSERT INTO producao.tbl_status_producao (status_producao, ordem)
VALUES
    ('ACABAMENTO', 10),
    ('ARAMADO', 20),
    ('COMPRAS', 30),
    ('ELÉTRICA', 40),
    ('EMBALAGEM', 50),
    ('ETIQUETAGEM/EXPEDIÇÃO', 60),
    ('FIBRA', 70),
    ('FILA', 80),
    ('MARCENARIA', 90),
    ('PINTURA', 100),
    ('PROJETOS', 110),
    ('REVESTIMENTO', 120),
    ('SEPARAÇÃO', 130),
    ('SERRALHERIA', 140),
    ('TERCEIRIZADO MARCENARIA', 150),
    ('TERCEIRIZADO SERRALHERIA', 160)
ON CONFLICT (status_producao)
DO UPDATE SET
    ordem = EXCLUDED.ordem,
    ativo = true;
